services:
  db:
    image: postgres:15-alpine
    container_name: aquaguard_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: aquaguard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aquaguard"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aquaguard_backend
    environment:
      PORT: 5001
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: aquaguard
      PGPASSWORD: postgrespassword
      PGPORT: 5432
      JWT_SECRET: aquaguard_jwt_secure_key_123
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aquaguard_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: aquaguard_prometheus
    volumes:
      - ./devops/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: aquaguard_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./devops/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./devops/grafana/dashboard_provider.yml:/etc/grafana/provisioning/dashboards/dashboard_provider.yml
      - ./devops/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    depends_on:
      - prometheus
    restart: always

volumes:
  pgdata:
    driver: local

